# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d07b1b6d1f6b95e7ecf04ba7b3b62a7167f296057f1cc300a9373f1bd91a351f48f9a081606537e7f98bf811bb146307cf6c32141fd7d89adb2bd02549b9813f

test:
  secret_key_base: 3a01098751b8d167128ec36a4466a6b070601534c2a2655d124aef617957298c10e9a874620937952ef7070fe77c63623f9ac3d0ddaece42045e756368b85774

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
